CC = g++
CFLAGS = -Wall -Wextra -pedantic -std=c++11

driver: driver.o sorts.o
	$(CC) $(CFLAGS) -o driver driver.o sorts.o

driver.o: driver.cpp sorts.h
	$(CC) $(CFLAGS) -c driver.cpp

sorts.o: sorts.cpp sorts.h
	$(CC) $(CFLAGS) -c sorts.cpp

clean:
	rm -f driver *.o
